node {
   def commit_id
   def dockerhub_user
   def dockerhub_pass
   def DOCKERHUB=credentials('dockerhub')
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
     sh 'DOCKERHUB_USER > dockerhub_user'
     sh 'DOCKERHUB_PASS > dockeerhub_pass'
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('login') {
      sh 'docker login -u ${dockerhub_user} -p ${dockerhub_pass}'
   }
   stage('docker build/push') {
       def app = docker.build("cristian321/docker-nodejs-demo:${commit_id}", '.').push()
   }
   stage('logout') {
      sh 'docker logout'
   }
}
