node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('login') {
      DOCKERHUB=credentials('dockerhub')
      sh 'echo $DOCKERHUB_PASSWORD >> ~/pass.txt'
      sh 'cat ~/pass.txt | docker login --username $DOCKERHUB_USER --password-stdin'
   }
   stage('docker build/push') {
       def app = docker.build("cristian321/docker-nodejs-demo:${commit_id}", '.').push()
   }
   stage('logout') {
      sh 'docker logout'
   }
}
